
print "imports"
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


#loading the file generated by API_request.py
# directory to adapt to your working environment
directory=r"C:\Users\Youssef\Documents\Data_Science\MyApps"
df=pd.read_csv(directory+"\\data_2.csv",sep=";")



#Let us start the exploration with some figures, then some descriptive statistics

#--------------------------------
print "Some figures"

#There are 3111 Meetup groups in Paris and its suburb
print (len(df))

#They are spread over 76 cities around Paris
print (len(df["city"].drop_duplicates()))
df["city"].drop_duplicates()[0:5]

#They cover 33 categories of activities: socializing, business,education...
print (len(df["categ_id"].drop_duplicates()))

#Group members goes from 1 to 22619
#The biggest Meetup group in Paris is INTERNATIONALS in Paris.
#A group that goes to the bar every week, that's not surprising :)
df.loc[df["member"]==22619,:]

# In total, there are 1,389,543 members (They are not distinct people
#since many persons join more than one group)
print (df["member"].sum())

#--------------------------------
print "Descriptive statistics"

#Group and members
#---in a boxplot
plt.figure()
plt.clf()
plt.cla()
plt.boxplot(df["member"])
plt.axis([0.5,1.5,0,1000])
plt.xlabel("Number of members per group")
plt.show()

#---in figures:
df["member"].describe()


#Members and categories
#---total members by category and sort
tab_category=df.groupby(by="categ_name",as_index=False)["member"].sum().sort_values(by="member",ascending=False)
#With 380k persons, the category with the highest amount of members is tech, French tech! 

#---In a pie chart
tab_category["member"]/=tab_category["member"].sum()
tab_category["member"]=(tab_category["member"]*100).round(1)

#Let's keep the first 6 categories (>5%) and include the rest in "Other"
from pylab import pie

fractions=list(tab_category["member"][0:6])
fractions.append(sum(tab_category["member"][6::]))
labels=list(tab_category["categ_name"][0:6])
labels.append("Other")

# plt.figure()
# plt.clf()
# plt.cla()
pie(fractions, labels=labels,
                autopct='%1.1f%%', shadow=False, startangle=90,counterclock=False,
				colors=('b', 'g', 'r', 'c', 'm', 'y', 'w'))
plt.title("Proportion of total members (1.4 M) by category")
plt.show()













